// Generated by tools/generate-content-registry.mjs. Do not edit by hand.
import lesson0007Raw from "virtual:book-lesson/LES-0007";
import lesson0008Raw from "virtual:book-lesson/LES-0008";
import lesson0006Raw from "virtual:book-lesson/LES-0006";
import lesson0010Raw from "virtual:book-lesson/LES-0010";
import lesson0011Raw from "virtual:book-lesson/LES-0011";
import lesson0012Raw from "virtual:book-lesson/LES-0012";
import lesson0013Raw from "virtual:book-lesson/LES-0013";
import lesson0014Raw from "virtual:book-lesson/LES-0014";
import lesson0015Raw from "virtual:book-lesson/LES-0015";
import lesson0016Raw from "virtual:book-lesson/LES-0016";
import lesson0009Raw from "virtual:book-lesson/LES-0009";
import lesson0017Raw from "virtual:book-lesson/LES-0017";
import lesson0018Raw from "virtual:book-lesson/LES-0018";
import lesson0019Raw from "virtual:book-lesson/LES-0019";
import lesson0020Raw from "virtual:book-lesson/LES-0020";
import lesson0021Raw from "virtual:book-lesson/LES-0021";
import lesson0022Raw from "virtual:book-lesson/LES-0022";
import lesson0023Raw from "virtual:book-lesson/LES-0023";
import lesson0024Raw from "virtual:book-lesson/LES-0024";
import lesson0025Raw from "virtual:book-lesson/LES-0025";
import lesson0026Raw from "virtual:book-lesson/LES-0026";
import assessment0001Value from "../../../book/assessments/linux/ASM-0001.json";
import assessment0002Value from "../../../book/assessments/linux/ASM-0002.json";
import assessment0003Value from "../../../book/assessments/linux/ASM-0003.json";
import assessment0004Value from "../../../book/assessments/foundations/ASM-0004.json";
import assessment0005Value from "../../../book/assessments/foundations/ASM-0005.json";
import assessment0006Value from "../../../book/assessments/foundations/ASM-0006.json";
import assessment0007Value from "../../../book/assessments/foundations/ASM-0007.json";
import assessment0008Value from "../../../book/assessments/foundations/ASM-0008.json";
import assessment0009Value from "../../../book/assessments/foundations/ASM-0009.json";
import assessment0010Value from "../../../book/assessments/engineering/ASM-0010.json";
import assessment0011Value from "../../../book/assessments/engineering/ASM-0011.json";
import assessment0012Value from "../../../book/assessments/engineering/ASM-0012.json";
import assessment0013Value from "../../../book/assessments/linux/ASM-0013.json";
import assessment0014Value from "../../../book/assessments/linux/ASM-0014.json";
import assessment0015Value from "../../../book/assessments/linux/ASM-0015.json";
import assessment0016Value from "../../../book/assessments/linux/ASM-0016.json";
import assessment0017Value from "../../../book/assessments/linux/ASM-0017.json";
import assessment0018Value from "../../../book/assessments/linux/ASM-0018.json";
import assessment0019Value from "../../../book/assessments/connectivity/ASM-0019.json";
import assessment0020Value from "../../../book/assessments/connectivity/ASM-0020.json";
import assessment0021Value from "../../../book/assessments/connectivity/ASM-0021.json";
import assessment0022Value from "../../../book/assessments/connectivity/ASM-0022.json";
import assessment0023Value from "../../../book/assessments/connectivity/ASM-0023.json";
import assessment0024Value from "../../../book/assessments/connectivity/ASM-0024.json";
import assessment0025Value from "../../../book/assessments/connectivity/ASM-0025.json";
import assessment0026Value from "../../../book/assessments/connectivity/ASM-0026.json";
import assessment0027Value from "../../../book/assessments/connectivity/ASM-0027.json";
import assessment0028Value from "../../../book/assessments/connectivity/ASM-0028.json";
import assessment0029Value from "../../../book/assessments/connectivity/ASM-0029.json";
import assessment0030Value from "../../../book/assessments/connectivity/ASM-0030.json";
import assessment0031Value from "../../../book/assessments/connectivity/ASM-0031.json";
import assessment0032Value from "../../../book/assessments/connectivity/ASM-0032.json";
import assessment0033Value from "../../../book/assessments/connectivity/ASM-0033.json";
import assessment0034Value from "../../../book/assessments/engineering/ASM-0034.json";
import assessment0035Value from "../../../book/assessments/engineering/ASM-0035.json";
import assessment0036Value from "../../../book/assessments/engineering/ASM-0036.json";
import assessment0037Value from "../../../book/assessments/engineering/ASM-0037.json";
import assessment0038Value from "../../../book/assessments/engineering/ASM-0038.json";
import assessment0039Value from "../../../book/assessments/engineering/ASM-0039.json";
import assessment0040Value from "../../../book/assessments/engineering/ASM-0040.json";
import assessment0041Value from "../../../book/assessments/engineering/ASM-0041.json";
import assessment0042Value from "../../../book/assessments/engineering/ASM-0042.json";
import assessment0043Value from "../../../book/assessments/engineering/ASM-0043.json";
import assessment0044Value from "../../../book/assessments/engineering/ASM-0044.json";
import assessment0045Value from "../../../book/assessments/engineering/ASM-0045.json";
import assessment0046Value from "../../../book/assessments/engineering/ASM-0046.json";
import assessment0047Value from "../../../book/assessments/engineering/ASM-0047.json";
import assessment0048Value from "../../../book/assessments/engineering/ASM-0048.json";
import assessment0049Value from "../../../book/assessments/engineering/ASM-0049.json";
import assessment0050Value from "../../../book/assessments/engineering/ASM-0050.json";
import assessment0051Value from "../../../book/assessments/engineering/ASM-0051.json";
import assessment0052Value from "../../../book/assessments/engineering/ASM-0052.json";
import assessment0053Value from "../../../book/assessments/engineering/ASM-0053.json";
import assessment0054Value from "../../../book/assessments/engineering/ASM-0054.json";
import assessment0055Value from "../../../book/assessments/engineering/ASM-0055.json";
import assessment0056Value from "../../../book/assessments/engineering/ASM-0056.json";
import assessment0057Value from "../../../book/assessments/engineering/ASM-0057.json";
import assessment0058Value from "../../../book/assessments/engineering/ASM-0058.json";
import assessment0059Value from "../../../book/assessments/engineering/ASM-0059.json";
import assessment0060Value from "../../../book/assessments/engineering/ASM-0060.json";
import assessment0061Value from "../../../book/assessments/reliability/ASM-0061.json";
import assessment0062Value from "../../../book/assessments/reliability/ASM-0062.json";
import assessment0063Value from "../../../book/assessments/reliability/ASM-0063.json";
import reference0001Value from "../../../book/references/REF-0001.json";
import reference0002Value from "../../../book/references/REF-0002.json";
import reference0003Value from "../../../book/references/REF-0003.json";
import reference0004Value from "../../../book/references/REF-0004.json";
import reference0005Value from "../../../book/references/REF-0005.json";
import reference0006Value from "../../../book/references/REF-0006.json";
import reference0007Value from "../../../book/references/REF-0007.json";
import reference0008Value from "../../../book/references/REF-0008.json";
import reference0009Value from "../../../book/references/REF-0009.json";
import reference0010Value from "../../../book/references/REF-0010.json";
import reference0011Value from "../../../book/references/REF-0011.json";
import reference0012Value from "../../../book/references/REF-0012.json";
import reference0013Value from "../../../book/references/REF-0013.json";
import reference0014Value from "../../../book/references/REF-0014.json";
import reference0015Value from "../../../book/references/REF-0015.json";
import reference0016Value from "../../../book/references/REF-0016.json";
import reference0017Value from "../../../book/references/REF-0017.json";
import reference0018Value from "../../../book/references/REF-0018.json";
import reference0019Value from "../../../book/references/REF-0019.json";
import reference0020Value from "../../../book/references/REF-0020.json";
import reference0021Value from "../../../book/references/REF-0021.json";
import reference0022Value from "../../../book/references/REF-0022.json";
import reference0023Value from "../../../book/references/REF-0023.json";
import reference0024Value from "../../../book/references/REF-0024.json";
import reference0025Value from "../../../book/references/REF-0025.json";
import reference0026Value from "../../../book/references/REF-0026.json";
import reference0027Value from "../../../book/references/REF-0027.json";
import reference0028Value from "../../../book/references/REF-0028.json";
import reference0029Value from "../../../book/references/REF-0029.json";
import reference0030Value from "../../../book/references/REF-0030.json";
import reference0031Value from "../../../book/references/REF-0031.json";
import reference0032Value from "../../../book/references/REF-0032.json";
import reference0033Value from "../../../book/references/REF-0033.json";
import reference0034Value from "../../../book/references/REF-0034.json";
import reference0035Value from "../../../book/references/REF-0035.json";
import reference0036Value from "../../../book/references/REF-0036.json";
import reference0037Value from "../../../book/references/REF-0037.json";
import reference0038Value from "../../../book/references/REF-0038.json";
import reference0039Value from "../../../book/references/REF-0039.json";
import reference0040Value from "../../../book/references/REF-0040.json";
import reference0041Value from "../../../book/references/REF-0041.json";
import reference0042Value from "../../../book/references/REF-0042.json";
import reference0043Value from "../../../book/references/REF-0043.json";
import reference0044Value from "../../../book/references/REF-0044.json";
import reference0045Value from "../../../book/references/REF-0045.json";
import reference0046Value from "../../../book/references/REF-0046.json";
import reference0047Value from "../../../book/references/REF-0047.json";
import reference0048Value from "../../../book/references/REF-0048.json";
import reference0049Value from "../../../book/references/REF-0049.json";
import reference0050Value from "../../../book/references/REF-0050.json";
import reference0051Value from "../../../book/references/REF-0051.json";
import reference0052Value from "../../../book/references/REF-0052.json";
import reference0053Value from "../../../book/references/REF-0053.json";
import reference0054Value from "../../../book/references/REF-0054.json";
import reference0055Value from "../../../book/references/REF-0055.json";
import reference0056Value from "../../../book/references/REF-0056.json";
import reference0057Value from "../../../book/references/REF-0057.json";
import reference0058Value from "../../../book/references/REF-0058.json";
import reference0059Value from "../../../book/references/REF-0059.json";
import reference0060Value from "../../../book/references/REF-0060.json";
import reference0061Value from "../../../book/references/REF-0061.json";
import reference0062Value from "../../../book/references/REF-0062.json";
import reference0063Value from "../../../book/references/REF-0063.json";
import reference0064Value from "../../../book/references/REF-0064.json";
import reference0065Value from "../../../book/references/REF-0065.json";
import reference0066Value from "../../../book/references/REF-0066.json";
import reference0067Value from "../../../book/references/REF-0067.json";
import reference0068Value from "../../../book/references/REF-0068.json";
import reference0069Value from "../../../book/references/REF-0069.json";
import reference0070Value from "../../../book/references/REF-0070.json";
import reference0071Value from "../../../book/references/REF-0071.json";
import reference0072Value from "../../../book/references/REF-0072.json";
import reference0073Value from "../../../book/references/REF-0073.json";
import reference0074Value from "../../../book/references/REF-0074.json";
import reference0075Value from "../../../book/references/REF-0075.json";
import reference0076Value from "../../../book/references/REF-0076.json";
import reference0077Value from "../../../book/references/REF-0077.json";
import reference0078Value from "../../../book/references/REF-0078.json";
import reference0079Value from "../../../book/references/REF-0079.json";
import reference0080Value from "../../../book/references/REF-0080.json";
import reference0081Value from "../../../book/references/REF-0081.json";
import reference0082Value from "../../../book/references/REF-0082.json";
import reference0083Value from "../../../book/references/REF-0083.json";
import reference0084Value from "../../../book/references/REF-0084.json";
import reference0085Value from "../../../book/references/REF-0085.json";
import reference0086Value from "../../../book/references/REF-0086.json";
import reference0087Value from "../../../book/references/REF-0087.json";
import reference0088Value from "../../../book/references/REF-0088.json";
import reference0089Value from "../../../book/references/REF-0089.json";
import reference0090Value from "../../../book/references/REF-0090.json";
import reference0091Value from "../../../book/references/REF-0091.json";
import reference0092Value from "../../../book/references/REF-0092.json";
import reference0093Value from "../../../book/references/REF-0093.json";
import reference0094Value from "../../../book/references/REF-0094.json";
import reference0095Value from "../../../book/references/REF-0095.json";
import reference0096Value from "../../../book/references/REF-0096.json";
import reference0097Value from "../../../book/references/REF-0097.json";
import reference0098Value from "../../../book/references/REF-0098.json";
import reference0099Value from "../../../book/references/REF-0099.json";
import reference0100Value from "../../../book/references/REF-0100.json";
import reference0101Value from "../../../book/references/REF-0101.json";
import reference0102Value from "../../../book/references/REF-0102.json";
import reference0103Value from "../../../book/references/REF-0103.json";
import reference0104Value from "../../../book/references/REF-0104.json";
import reference0105Value from "../../../book/references/REF-0105.json";
import reference0106Value from "../../../book/references/REF-0106.json";
import reference0107Value from "../../../book/references/REF-0107.json";
import reference0108Value from "../../../book/references/REF-0108.json";
import reference0109Value from "../../../book/references/REF-0109.json";
import reference0110Value from "../../../book/references/REF-0110.json";
import reference0111Value from "../../../book/references/REF-0111.json";
import reference0112Value from "../../../book/references/REF-0112.json";
import reference0113Value from "../../../book/references/REF-0113.json";
import reference0114Value from "../../../book/references/REF-0114.json";
import reference0115Value from "../../../book/references/REF-0115.json";
import reference0116Value from "../../../book/references/REF-0116.json";
import reference0117Value from "../../../book/references/REF-0117.json";
import reference0118Value from "../../../book/references/REF-0118.json";
import reference0119Value from "../../../book/references/REF-0119.json";
import reference0120Value from "../../../book/references/REF-0120.json";
import reference0121Value from "../../../book/references/REF-0121.json";
import reference0122Value from "../../../book/references/REF-0122.json";
import reference0123Value from "../../../book/references/REF-0123.json";
import reference0124Value from "../../../book/references/REF-0124.json";
import reference0125Value from "../../../book/references/REF-0125.json";
import reference0126Value from "../../../book/references/REF-0126.json";
import reference0127Value from "../../../book/references/REF-0127.json";
import reference0128Value from "../../../book/references/REF-0128.json";
import reference0129Value from "../../../book/references/REF-0129.json";
import reference0130Value from "../../../book/references/REF-0130.json";
import reference0131Value from "../../../book/references/REF-0131.json";
import reference0132Value from "../../../book/references/REF-0132.json";
import reference0133Value from "../../../book/references/REF-0133.json";
import reference0134Value from "../../../book/references/REF-0134.json";
import reference0135Value from "../../../book/references/REF-0135.json";
import reference0136Value from "../../../book/references/REF-0136.json";
import reference0137Value from "../../../book/references/REF-0137.json";
import reference0138Value from "../../../book/references/REF-0138.json";
import reference0139Value from "../../../book/references/REF-0139.json";
import reference0140Value from "../../../book/references/REF-0140.json";
import reference0141Value from "../../../book/references/REF-0141.json";
import reference0142Value from "../../../book/references/REF-0142.json";
import reference0143Value from "../../../book/references/REF-0143.json";
import reference0144Value from "../../../book/references/REF-0144.json";
import reference0145Value from "../../../book/references/REF-0145.json";
import reference0146Value from "../../../book/references/REF-0146.json";
import reference0147Value from "../../../book/references/REF-0147.json";
import reference0148Value from "../../../book/references/REF-0148.json";
import reference0149Value from "../../../book/references/REF-0149.json";
import reference0150Value from "../../../book/references/REF-0150.json";
import reference0151Value from "../../../book/references/REF-0151.json";
import reference0152Value from "../../../book/references/REF-0152.json";
import reference0153Value from "../../../book/references/REF-0153.json";
import reference0154Value from "../../../book/references/REF-0154.json";
import reference0155Value from "../../../book/references/REF-0155.json";
import reference0156Value from "../../../book/references/REF-0156.json";
import reference0157Value from "../../../book/references/REF-0157.json";
import reference0158Value from "../../../book/references/REF-0158.json";
import reference0159Value from "../../../book/references/REF-0159.json";
import reference0160Value from "../../../book/references/REF-0160.json";
import reference0161Value from "../../../book/references/REF-0161.json";
import reference0162Value from "../../../book/references/REF-0162.json";
import reference0163Value from "../../../book/references/REF-0163.json";
import reference0164Value from "../../../book/references/REF-0164.json";
import reference0165Value from "../../../book/references/REF-0165.json";
import reference0166Value from "../../../book/references/REF-0166.json";
import reference0167Value from "../../../book/references/REF-0167.json";
import reference0168Value from "../../../book/references/REF-0168.json";
import reference0169Value from "../../../book/references/REF-0169.json";
import reference0170Value from "../../../book/references/REF-0170.json";
import reference0171Value from "../../../book/references/REF-0171.json";
import reference0172Value from "../../../book/references/REF-0172.json";

export const generatedLessonSources: readonly string[] = [
  lesson0007Raw,
  lesson0008Raw,
  lesson0006Raw,
  lesson0010Raw,
  lesson0011Raw,
  lesson0012Raw,
  lesson0013Raw,
  lesson0014Raw,
  lesson0015Raw,
  lesson0016Raw,
  lesson0009Raw,
  lesson0017Raw,
  lesson0018Raw,
  lesson0019Raw,
  lesson0020Raw,
  lesson0021Raw,
  lesson0022Raw,
  lesson0023Raw,
  lesson0024Raw,
  lesson0025Raw,
  lesson0026Raw,
];

export const generatedAssessmentValues: readonly unknown[] = [
  assessment0001Value,
  assessment0002Value,
  assessment0003Value,
  assessment0004Value,
  assessment0005Value,
  assessment0006Value,
  assessment0007Value,
  assessment0008Value,
  assessment0009Value,
  assessment0010Value,
  assessment0011Value,
  assessment0012Value,
  assessment0013Value,
  assessment0014Value,
  assessment0015Value,
  assessment0016Value,
  assessment0017Value,
  assessment0018Value,
  assessment0019Value,
  assessment0020Value,
  assessment0021Value,
  assessment0022Value,
  assessment0023Value,
  assessment0024Value,
  assessment0025Value,
  assessment0026Value,
  assessment0027Value,
  assessment0028Value,
  assessment0029Value,
  assessment0030Value,
  assessment0031Value,
  assessment0032Value,
  assessment0033Value,
  assessment0034Value,
  assessment0035Value,
  assessment0036Value,
  assessment0037Value,
  assessment0038Value,
  assessment0039Value,
  assessment0040Value,
  assessment0041Value,
  assessment0042Value,
  assessment0043Value,
  assessment0044Value,
  assessment0045Value,
  assessment0046Value,
  assessment0047Value,
  assessment0048Value,
  assessment0049Value,
  assessment0050Value,
  assessment0051Value,
  assessment0052Value,
  assessment0053Value,
  assessment0054Value,
  assessment0055Value,
  assessment0056Value,
  assessment0057Value,
  assessment0058Value,
  assessment0059Value,
  assessment0060Value,
  assessment0061Value,
  assessment0062Value,
  assessment0063Value,
];

export const generatedReferenceValues: readonly unknown[] = [
  reference0001Value,
  reference0002Value,
  reference0003Value,
  reference0004Value,
  reference0005Value,
  reference0006Value,
  reference0007Value,
  reference0008Value,
  reference0009Value,
  reference0010Value,
  reference0011Value,
  reference0012Value,
  reference0013Value,
  reference0014Value,
  reference0015Value,
  reference0016Value,
  reference0017Value,
  reference0018Value,
  reference0019Value,
  reference0020Value,
  reference0021Value,
  reference0022Value,
  reference0023Value,
  reference0024Value,
  reference0025Value,
  reference0026Value,
  reference0027Value,
  reference0028Value,
  reference0029Value,
  reference0030Value,
  reference0031Value,
  reference0032Value,
  reference0033Value,
  reference0034Value,
  reference0035Value,
  reference0036Value,
  reference0037Value,
  reference0038Value,
  reference0039Value,
  reference0040Value,
  reference0041Value,
  reference0042Value,
  reference0043Value,
  reference0044Value,
  reference0045Value,
  reference0046Value,
  reference0047Value,
  reference0048Value,
  reference0049Value,
  reference0050Value,
  reference0051Value,
  reference0052Value,
  reference0053Value,
  reference0054Value,
  reference0055Value,
  reference0056Value,
  reference0057Value,
  reference0058Value,
  reference0059Value,
  reference0060Value,
  reference0061Value,
  reference0062Value,
  reference0063Value,
  reference0064Value,
  reference0065Value,
  reference0066Value,
  reference0067Value,
  reference0068Value,
  reference0069Value,
  reference0070Value,
  reference0071Value,
  reference0072Value,
  reference0073Value,
  reference0074Value,
  reference0075Value,
  reference0076Value,
  reference0077Value,
  reference0078Value,
  reference0079Value,
  reference0080Value,
  reference0081Value,
  reference0082Value,
  reference0083Value,
  reference0084Value,
  reference0085Value,
  reference0086Value,
  reference0087Value,
  reference0088Value,
  reference0089Value,
  reference0090Value,
  reference0091Value,
  reference0092Value,
  reference0093Value,
  reference0094Value,
  reference0095Value,
  reference0096Value,
  reference0097Value,
  reference0098Value,
  reference0099Value,
  reference0100Value,
  reference0101Value,
  reference0102Value,
  reference0103Value,
  reference0104Value,
  reference0105Value,
  reference0106Value,
  reference0107Value,
  reference0108Value,
  reference0109Value,
  reference0110Value,
  reference0111Value,
  reference0112Value,
  reference0113Value,
  reference0114Value,
  reference0115Value,
  reference0116Value,
  reference0117Value,
  reference0118Value,
  reference0119Value,
  reference0120Value,
  reference0121Value,
  reference0122Value,
  reference0123Value,
  reference0124Value,
  reference0125Value,
  reference0126Value,
  reference0127Value,
  reference0128Value,
  reference0129Value,
  reference0130Value,
  reference0131Value,
  reference0132Value,
  reference0133Value,
  reference0134Value,
  reference0135Value,
  reference0136Value,
  reference0137Value,
  reference0138Value,
  reference0139Value,
  reference0140Value,
  reference0141Value,
  reference0142Value,
  reference0143Value,
  reference0144Value,
  reference0145Value,
  reference0146Value,
  reference0147Value,
  reference0148Value,
  reference0149Value,
  reference0150Value,
  reference0151Value,
  reference0152Value,
  reference0153Value,
  reference0154Value,
  reference0155Value,
  reference0156Value,
  reference0157Value,
  reference0158Value,
  reference0159Value,
  reference0160Value,
  reference0161Value,
  reference0162Value,
  reference0163Value,
  reference0164Value,
  reference0165Value,
  reference0166Value,
  reference0167Value,
  reference0168Value,
  reference0169Value,
  reference0170Value,
  reference0171Value,
  reference0172Value,
];
