apiVersion: 1

deleteDatasources:
  - name: LES-0028 Prometheus
    orgId: 1

datasources:
  - name: LES-0028 Prometheus
    uid: les0028-prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      manageAlerts: false
      prometheusType: Prometheus
      prometheusVersion: 3.13.2
      timeInterval: 1s
