apiVersion: v1
kind: Pod
metadata:
  name: over-quota-example
  namespace: team-a
spec:
  serviceAccountName: runtime-payments-api
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: app
      image: atlas-platform-demo:1.0.0
      imagePullPolicy: Never
      resources:
        requests:
          cpu: "3"
          memory: 64Mi
        limits:
          cpu: "3"
          memory: 64Mi
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop: ["ALL"]
